language: c
os:
  - linux
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull -t learn-ocaml --target program .; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -c 'docker run --rm -v $(pwd)/.:/repository learn-ocaml -- build'; fi
